
name: Update download history

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout mod database
        uses: actions/checkout@v4
        with:
          repository: Raicuparta/ow-mod-db
          ref: master
          fetch-depth: 0
          path: ow-mod-db
          
      - name: Get database log 
        run: |
          cd ow-mod-db
          git log -p > log.txt
          cd ..

      - name: Setup .NET 8 runtime
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        
      - name: Convert log.txt to json
        run: |
          mkdir _site
          dotnet run -- "ow-mod-db/log.txt" > _site/download-history.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
